AWSTemplateFormatVersion: '2010-09-09'
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'zread-${AWS::AccountId}-${AWS::Region}'
      VersioningConfiguration:
        Status: Enabled
  
  BedrockKnowledgeBase:
    Type: AWS::Bedrock::KnowledgeBase
    Properties:
      Name: zread-kb
      RoleArn: !GetAtt KnowledgeBaseRole.Arn
      KnowledgeBaseConfiguration:
        Type: VECTOR
        VectorKnowledgeBaseConfiguration:
          EmbeddingModelArn: arn:aws:bedrock:us-east-1::foundation-model/amazon.titan-embed-text-v1
  
  RepoProcessorLambda:
    Type: AWS::Lambda::Function
    Properties:
      CodeUri: src/lambda/
      Handler: repo-processor.lambda_handler
      Runtime: python3.12
      Role: !GetAtt LambdaRole.Arn
      Timeout: 900  # 15 mins
  
  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      SourceAction: GitHub  # SSH or HTTPS
      DeployAction: Lambda + KB